# Generated by Django 2.0.5 on 2018-05-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=11, max_length=32),
            preserve_default=False,
        ),
    ]
