# Generated by Django 2.0.5 on 2018-05-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
